services:
  #--- BACKEND: NGINX ---
  nginx:
    container_name: nginx-prod
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      # Laravel app (for API routes)
      - ./backend:/var/www
      # Built React app (for frontend)
      - ./frontend/public/build:/var/www/html
      # Nginx configuration
      - ./backend/docker/production/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - php-fpm
    networks:
      - myapp-network

  #--- BACKEND: PHP-FPM ---
  php-fpm:
    container_name: php-fpm-prod
    build:
      context: ./backend
      dockerfile: ./docker/common/php-fpm/Dockerfile
      target: production
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/var/www
    networks:
      - myapp-network

networks:
  myapp-network:
