services:
  nginx:
    container_name: nginx
    build:
      context: .
      dockerfile: ./docker/production/nginx/Dockerfile
    ports:
      - "443:443"
    volumes:
      - public-assets:/var/www/public/build:ro
      - storage-production:/var/www/storage:ro
    restart: unless-stopped
    networks:
      - app-network
    depends_on:
      - php-fpm

  php-fpm:
    container_name: php-fpm
    build:
      context: .
      dockerfile: ./docker/common/php-fpm/Dockerfile
      target: production
      args:
        UID: ${UID:-1000}
        GID: ${GID:-1000}
    user: "${UID:-1000}:${GID:-1000}"
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - public-assets:/var/www/public/build
      - storage-production:/var/www/storage
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "php-fpm-healthcheck || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 3

networks:
  app-network:

volumes:
  public-assets:
  storage-production: